services:
  ros_audio:
    build: .
    image: ros_noetic_audio
    container_name: ros_audio_container
    hostname: ros_audio_container
    command: ["bash", "-lc", "tail -f /dev/null"]
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - GDK_DISABLE_SHM=1
      - NO_AT_BRIDGE=1
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - PULSE_COOKIE=/root/.config/pulse/cookie
      - ROS_MASTER_URI=${ROS_MASTER_URI:-http://ros_audio_container:11311}
      - ROS_HOSTNAME=${ROS_HOSTNAME:-ros_audio_container}
    volumes:
      - /dev/snd:/dev/snd
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME_DIR}/.config/pulse/cookie:/root/.config/pulse/cookie
      - .:/root/workspace
    devices:
      - /dev/snd:/dev/snd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    group_add:
      - audio
    stdin_open: true
    tty: true
    networks:
      - ros_net

networks:
  ros_net:
    name: ros_net
    driver: bridge
